## CHANGE 更改此处为你的附属名称
name: XingchenExpansion

## CHANGE 更改此处为你的名称
author: xingchen

## CHANGE 这是对你插件的介绍
description: 一个粘液科技附属,为粘液科技扩展更多内容

## CHANGE 指向你的 JavaPlugin 主类
main: me.xingchen.XingchenExpansion.XingchenExpansion

## 你可以更改为你的项目仓库地址，或者你的个人网站。你也可以移除此项目。
website: https://github.com/Slimefun/Addon-Template

## 该值将在构建时被自动替换为pom.xml中定义的版本。
## 不要更改此项目。
version: ${project.version}

## 这是运行该附属所需的最低MC版本。
api-version: 1.21.4

## 指定 Slimefun 作为依赖项，必须
depend:
- Slimefun